# Frappe CRM LZC Manifest
# 基于 Frappe CRM Docker Compose 配置转换

# 基本信息
package: cloud.lazycat.app.frappe-crm
version: 1.0.0
name: Frappe CRM
description: 功能完整的开源 CRM 系统，基于 Frappe Framework
author: Lazycat Apps
homepage: https://github.com/frappe/crm
license: AGPL-3.0

# 应用核心配置
application:
  # 应用子域名
  subdomain: frappe-crm

  # 后台常驻任务
  background_task: true

  # 单实例模式
  multi_instance: false

  # HTTP 路由规则
  routes:
    - /=http://frappe-crm:8000

  # 依赖服务（必须先启动并健康检查通过）
  depends_on:
    - mariadb
    - redis

  # 环境变量
  environment:
    - SHELL=/bin/bash

  # 健康检查
  health_check:
    test_url: http://127.0.0.1:8000
    start_period: 120s  # Frappe 初始化需要较长时间
    disable: false

# Docker 容器服务配置
services:
  # 主应用服务
  frappe-crm:
    # 使用预构建的离线镜像，包含所有 Frappe 和 CRM 代码
    image: frappe-crm-offline:latest

    # 启动命令 - 执行优化后的 init.sh 脚本
    # 脚本会从镜像复制预构建内容到持久化存储
    # command: bash /home/frappe/init.sh

    # 环境变量
    environment:
      - SHELL=/bin/bash

    # 持久化存储
    # binds:
    #   # Frappe bench 工作目录持久化到 /lzcapp/var
    #   - /lzcapp/var/frappe-bench:/home/frappe/frappe-bench

  # MariaDB 数据库服务
  mariadb:
    image: mariadb:10.8

    # 数据库启动参数
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-character-set-client-handshake --skip-innodb-read-only-compressed

    # 环境变量
    environment:
      - MYSQL_ROOT_PASSWORD=123

    # 数据持久化
    binds:
      - /lzcapp/var/mysql:/var/lib/mysql

    # 资源限制
    mem_limit: 1G

    # 健康检查
    health_check:
      test:
        - CMD
        - mariadb-admin
        - ping
        - -h
        - localhost
        - -u
        - root
        - -p123
      start_period: 30s
      disable: false

  # Redis 缓存服务
  redis:
    image: redis:alpine

    # 资源限制
    mem_limit: 256M

    # 健康检查
    health_check:
      test:
        - CMD
        - redis-cli
        - ping
      start_period: 10s
      disable: false
