# Frappe CRM LZC Manifest
# 基于 Frappe CRM Docker Compose 配置转换

# 基本信息
package: cloud.lazycat.app.xiao.frappe-crm
version: 1.0.0

name: Frappe CRM
keywords: frappe,crm,erp,opensource
description: 功能完整的开源 CRM 系统，基于 Frappe Framework

author: xiao
homepage: https://github.com/frappe/crm
license: AGPL-3.0

locales:
  zh:
    name: Frappe CRM
    description: 功能完整的开源 CRM 系统，基于 Frappe Framework
  en:
    name: Frappe CRM
    description: A full-featured open source CRM system based on Frappe Framework


# 应用核心配置
application:
  # 应用子域名
  subdomain: frappe-crm

  # 后台常驻任务
  background_task: true

  # 单实例模式
  multi_instance: false

  # HTTP 路由规则
  routes:
    - /=http://frappe-crm:8000

  # 依赖服务（必须先启动并健康检查通过）
  depends_on:
    - mariadb
    - redis

  health_check:
    test_url: http://frappe-crm:8000
    start_period: 120s

# Docker 容器服务配置
services:
  # 主应用服务
  frappe-crm:
    # 使用预构建的离线镜像，包含所有 Frappe 和 CRM 代码
    # image: registry.lazycat.cloud/liu/lazycatapps/frappe-crm:fa8d45cbbf7c86de
    image: dev.minicat.heiyu.space/lzc/nanjingfm761/frappe-crm:v2

    # 启动命令 - 执行优化后的 init.sh 脚本
    # 脚本会从镜像复制预构建内容到持久化存储
    # command: bash /home/frappe/init.sh

    # 环境变量
    environment:
      - SHELL=/bin/bash

    # # 持久化存储
    binds:
      # Frappe bench 工作目录持久化到 /lzcapp/var
      - /lzcapp/var/frappe-bench:/home/frappe/frappe-bench

    setup_script: |
      chown -R frappe:frappe /home/frappe/frappe-bench

  # MariaDB 数据库服务
  mariadb:
    image: registry.lazycat.cloud/xiao/library/mariadb:ec6c67c9b50bc2bb

    # 数据库启动参数
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-character-set-client-handshake --skip-innodb-read-only-compressed

    # 环境变量
    environment:
      - MYSQL_ROOT_PASSWORD=123

    # 数据持久化
    binds:
      - /lzcapp/var/mysql:/var/lib/mysql

    # 资源限制
    mem_limit: 1G

    # 健康检查
    health_check:
      test:
        - CMD
        - mariadb-admin
        - ping
        - -h
        - localhost
        - -u
        - root
        - -p123
      start_period: 30s
      disable: false

  # Redis 缓存服务
  redis:
    image: registry.lazycat.cloud/xiao/library/redis:a16a669304389bd5

    # 资源限制
    mem_limit: 256M

    # 健康检查
    health_check:
      test:
        - CMD
        - redis-cli
        - ping
      start_period: 10s
      disable: false

unsupported_platforms:
  - ios
  - android
